// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfvyrsmzzwmubckdymtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdnlyc216endtdWJja2R5bXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTY3OTEsImV4cCI6MjA2Mjk5Mjc5MX0.ZCWVQB4c41Qx7RXtgwprkyBC1DZLmtRaz3ATNt4bcfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);